micronaut:
  application:
    name: data-upload
  serde:
    enabled: true
  server:
    enabled: false

ingestion:
  bucket-name: sales-data

aws:
  region: eu-west-1
  services:
   kinesis:
     stream: sales-stream


logging:
  level:
    root: INFO
    software.amazon.awssdk: WARN
