micronaut:
  application:
    name: sales-ingester
  serde:
    enabled: true
  server:
    enabled: false

ingestion:
  bucket-name: ${SALES_BUCKET_NAME:sales-data}

aws:
  region: ${AWS_REGION:eu-west-1}
  services:
   kinesis:
     stream: ${KINESIS_STREAM_NAME:sales-stream}


logging:
  level:
    root: INFO
    software.amazon.awssdk: WARN
