micronaut:
  server:
    enabled: true
    port: 8080
  http:
    client:
      read-timeout: 30s

ingestion:
  bucket-name: sales-data

aws:
  region: us-east-1
  access-key-id: test
  secret-access-key: test
  services:
    kinesis:
      endpoint-override: http://localhost:4566
    s3:
      endpoint-override: http://localhost:4566
  s3:
    path-style-access-enabled: true

logging:
  level:
    root: DEBUG
