micronaut:
  application:
    name: sales-cleanup
  server:
    enabled: false

ingestion:
  bucket-name: ${SALES_BUCKET_NAME:sales-data}

aws:
  region: eu-west-1


logging:
  level:
    root: INFO
    software.amazon.awssdk: WARN