ingestion:
  bucket-name: sales-data

aws:
  region: us-east-1
  access-key-id: test
  secret-access-key: test
  services:
    s3:
      endpoint-override: http://localhost:4566
  s3:
    path-style-access-enabled: true