mybatis:
  environment: local

aws:
  account-id: 000000000000
  region: us-east-1
  access-key-id: test
  secret-access-key: test
  services:
    kinesis:
      endpoint-override: http://localhost:4566
    dynamodb:
      endpoint-override: http://localhost:4566
    cloudwatch:
      endpoint-override: http://localhost:4566
    sqs:
      endpoint-override: http://localhost:4566
      queueUrl: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/sales-queue

grpc:
  channels:
    fx:
      address: "localhost:9028"
      plaintext: true

logging:
  level:
    root: DEBUG