micronaut:
  application:
    name: sales-analyzer-job
  env:
    deduce-environment: false

liquibase:
  enabled: true
  datasources:
    default:
      change-log: classpath:db/changelog/db.changelog-master.yml

datasources:
  default:
    driverClassName: org.postgresql.Driver
    username: ${TIMESCALE_USERNAME:admin}
    password: ${TIMESCALE_PASSWORD:admin}
    maximumPoolSize: 5
    minimumIdle: 1
    autoCommit: false

aws:
   region: ${AWS_REGION:eu-west-1}
   services:
     kinesis:
       stream: ${KINESIS_STREAM_NAME:sales-stream}
       windows:
        size-minutes: 1


grpc:
  timeout-ms: 10000
  process-timeout-ms: 15000
  client:
    plaintext: true
  channels:
    fx:
      address: "${FX_SERVICE_HOST}:${FX_SERVICE_PORT}"
      plaintext: true

default-currency: ${DEFAULT_CURRENCY:EUR}

logging:
  level:
    root: INFO
    software.amazon.awssdk: WARN