mybatis:
  environment: aws

datasources:
  default:
    url: jdbc:postgresql://${RDS_ENDPOINT}:5432/metrics

aws:
  services:
    sqs:
      queueUrl: ${SQS_QUEUE_URL}
  rds:
    secret-id: ${RDS_CREDENTIALS_ARN}