micronaut:
  application:
    name: sales-analyzer-job

liquibase:
  enabled: true
  datasources:
    default:
      change-log: classpath:db/changelog/db.changelog-master.yml

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/sales_metrics
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
    maximumPoolSize: 5
    minimumIdle: 1
    autoCommit: false

aws:
   account-id: ${AWS_ACCOUNT_ID:000000000000}
   region: us-east-2
   access-key-id: ${AWS_KEY_ID}
   secret-access-key: ${AWS_SECRET_ACCESS_KEY}
   services:
     kinesis:
       stream: sales-stream
       windows:
        size-minutes: 1
     sqs:
       queueUrl: ${SQS_QUEUE_URL}


grpc:
  channels:
    fx:
      address: "dns:///fx-service.internal:9028"
      plaintext: true

default-currency: EUR

logging:
  level:
    root: INFO
    software.amazon.awssdk: WARN